FROM node:18-alpine

WORKDIR /app

COPY package.json yarn.lock /app/

ENV CYPRESS_INSTALL_BINARY=0

RUN yarn install && yarn cache clean

COPY . /app

RUN yarn build

ENV HOST 0.0.0.0

EXPOSE 3000

CMD ["yarn", "start"]
